name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: checkout files
        uses: actions/checkout@v1
      - name: List Files after checkout
        run: |
          pwd
          ls -a