name: shell commands

on: [push]

jobs: 
  run-shell-command: 
     runs-on: ubuntu-latest
     steps: 
       - name: echo a string 
         run: echo "Hello world to Ganesh Github actions..."
       - name: multiline script
         run: |
           node -v
           npm -v

         
